### ISSUE TITLE
add facebook to organization

### ISSUE THREAD

**Issue by gimmyxd** [PopescuGheorghe/mentors4me-api#11]

**Comment by IuresiIssabel** [comment]
What is the requested format? User does not know what he/she can write in this field.

![uploads/6585d1d5-f9b8-4f9d-b5f4-bedca0cff813/Screenshot_5.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6585d1d5-f9b8-4f9d-b5f4-bedca0cff813%2FScreenshot_5.png)
